### ISSUE TITLE
"login --refresh" without a profile spams the terminal

### ISSUE THREAD

**Issue by mo-gr** [zalando-stups/mai#8]
When `login --refresh` is called without an explicit profile and the last login was over an hour ago, mai goes into a loop and spams the stdout with "Waiting 54 minutes before refreshing credentials.. OK" messages.

This neither happens when that last login was less then an hour ago nor when an explicit profile is specified to the login command.

Environment: Mac OS X 10.10.3
Version: Mai 0.14

**Comment by tuxlife** [comment]
fixed in 0.17
